repos:
-   repo: https://github.com/ambv/black
    rev: "19.10b0"
    hooks:
    - id: black
      language_version: python3.8
      types: [python]
      exclude: "setup.py"
-   repo: local
    hooks:
    - id: pytest
      name: pytest
      language: system
      entry: pytest
      pass_filenames: false
      always_run: true
      stages: [commit, push]
    - id: mypy
      name: mypy
      language: system
      files: ^unweaver/
      entry: mypy unweaver/
      pass_filenames: false
      always_run: true
      stages: [commit, push]
